<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Cache;

class TradingController extends Controller
{
    /**
     * Get OHLC data from Binance API
     * 
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getOHLC(Request $request)
    {
        try {
            $symbol = $request->input('symbol', 'BTCUSDT'); // Default to BTC/USDT
            $interval = $request->input('interval', '1m'); // Default to 1 minute
            $limit = $request->input('limit', 500); // Default to 500 candles
            
            // Validate interval
            $validIntervals = ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M'];
            if (!in_array($interval, $validIntervals)) {
                return response()->json([
                    'success' => false,
                    'error' => 'Invalid interval. Valid intervals: ' . implode(', ', $validIntervals)
                ], 400);
            }
            
            // Validate limit (max 1000 for Binance)
            $limit = min(max(1, (int)$limit), 1000);
            
            // Call Binance API
            $response = Http::timeout(10)->get('https://api.binance.com/api/v3/klines', [
                'symbol' => strtoupper($symbol),
                'interval' => $interval,
                'limit' => $limit,
            ]);
            
            if (!$response->successful()) {
                Log::error('Binance API error', [
                    'status' => $response->status(),
                    'body' => $response->body(),
                ]);
                
                return response()->json([
                    'success' => false,
                    'error' => 'Failed to fetch data from Binance API'
                ], 500);
            }
            
            $data = $response->json();
            
            // Transform Binance format to Lightweight Charts format
            // Binance format: [Open time, Open, High, Low, Close, Volume, ...]
            // Lightweight Charts format: { time: timestamp, open: number, high: number, low: number, close: number, volume: number }
            $ohlcData = array_map(function ($candle) {
                return [
                    'time' => (int)($candle[0] / 1000), // Convert milliseconds to seconds
                    'open' => (float)$candle[1],
                    'high' => (float)$candle[2],
                    'low' => (float)$candle[3],
                    'close' => (float)$candle[4],
                    'volume' => (float)$candle[5],
                ];
            }, $data);
            
            return response()->json([
                'success' => true,
                'data' => $ohlcData,
                'symbol' => strtoupper($symbol),
                'interval' => $interval,
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::getOHLC error', [
                'message' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred while fetching OHLC data'
            ], 500);
        }
    }
    
    /**
     * Get current price for a symbol (from cache - generated by Price Engine)
     */
    public function getCurrentPrice(Request $request)
    {
        try {
            $symbol = $request->input('symbol', 'BTCUSDT');
            $price = \Illuminate\Support\Facades\Cache::get("{$symbol}_PRICE", $this->getDefaultPrice($symbol));
            
            return response()->json([
                'success' => true,
                'symbol' => $symbol,
                'price' => (float)$price,
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::getCurrentPrice error', [
                'message' => $e->getMessage(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred while fetching price'
            ], 500);
        }
    }
    
    /**
     * Get historical candles from database
     * Fallback to Binance if no data in database
     */
    public function getCandles(Request $request)
    {
        try {
            $symbol = $request->input('symbol', 'BTCUSDT');
            $timeframe = $request->input('timeframe', '15m');
            $limit = min((int)$request->input('limit', 500), 1000);
            
            $candles = \App\Models\Candle::where('symbol', $symbol)
                ->where('timeframe', $timeframe)
                ->orderBy('time', 'desc')
                ->limit($limit)
                ->get();
            
            // If no candles in database, fallback to Binance or generate sample data
            if ($candles->isEmpty()) {
                // Try to get from Binance first
                try {
                    $binanceData = $this->getOHLC($request);
                    if ($binanceData->getStatusCode() === 200) {
                        $data = json_decode($binanceData->getContent(), true);
                        return response()->json([
                            'success' => true,
                            'data' => $data['data'] ?? [],
                            'symbol' => $symbol,
                            'timeframe' => $timeframe,
                            'source' => 'binance',
                        ]);
                    }
                } catch (\Exception $e) {
                    // If Binance fails, generate sample data
                    Log::warning('Failed to fetch from Binance, generating sample data', [
                        'error' => $e->getMessage(),
                    ]);
                }
                
                // Generate sample candles
                $candles = $this->generateSampleCandles($symbol, $timeframe, $limit);
            } else {
                $candles = $candles->reverse()->map(function ($candle) {
                    return [
                        'time' => (int)$candle->time,
                        'open' => (float)$candle->open,
                        'high' => (float)$candle->high,
                        'low' => (float)$candle->low,
                        'close' => (float)$candle->close,
                        'volume' => (float)$candle->volume,
                    ];
                })->values();
            }
            
            return response()->json([
                'success' => true,
                'data' => $candles,
                'symbol' => $symbol,
                'timeframe' => $timeframe,
                'source' => 'database',
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::getCandles error', [
                'message' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred while fetching candles'
            ], 500);
        }
    }
    
    /**
     * Generate sample candles for initial display
     */
    private function generateSampleCandles(string $symbol, string $timeframe, int $limit): array
    {
        $basePrice = $this->getDefaultPrice($symbol);
        $candles = [];
        $now = now()->timestamp;
        
        // Calculate timeframe in seconds
        $timeframeSeconds = match($timeframe) {
            '1m' => 60,
            '5m' => 300,
            '15m' => 900,
            '1h' => 3600,
            '4h' => 14400,
            '1d' => 86400,
            default => 900,
        };
        
        $currentPrice = $basePrice;
        
        for ($i = $limit - 1; $i >= 0; $i--) {
            $time = $now - ($i * $timeframeSeconds);
            
            // Random price movement
            $change = rand(-50, 50);
            $open = $currentPrice;
            $close = $open + $change;
            $high = max($open, $close) + rand(10, 30);
            $low = min($open, $close) - rand(10, 30);
            $volume = rand(100, 1000);
            
            $candles[] = [
                'time' => $time,
                'open' => (float)$open,
                'high' => (float)$high,
                'low' => (float)$low,
                'close' => (float)$close,
                'volume' => (float)$volume,
            ];
            
            $currentPrice = $close;
        }
        
        return $candles;
    }
    
    /**
     * Place a trading bet
     */
    public function placeBet(Request $request)
    {
        try {
            $user = $request->user();
            if (!$user) {
                return response()->json([
                    'success' => false,
                    'error' => 'Unauthorized'
                ], 401);
            }
            
            $request->validate([
                'symbol' => 'required|string',
                'direction' => 'required|in:up,down',
                'amount' => 'required|numeric|min:1',
            ]);
            
            $symbol = $request->input('symbol');
            $direction = $request->input('direction');
            $amount = (float)$request->input('amount');
            
            // Check balance
            if ($user->balance < $amount) {
                return response()->json([
                    'success' => false,
                    'error' => 'Số dư không đủ'
                ], 400);
            }
            
            // Get current price
            $entryPrice = Cache::get("{$symbol}_PRICE", $this->getDefaultPrice($symbol));
            
            // Calculate current round time (60 seconds per round)
            $now = now()->timestamp;
            $roundTime = floor($now / 60) * 60;
            
            // Check if user already has a bet for this round
            $existingBet = \App\Models\TradingBet::where('user_id', $user->id)
                ->where('symbol', $symbol)
                ->where('round_time', $roundTime)
                ->where('status', 'pending')
                ->first();
            
            if ($existingBet) {
                return response()->json([
                    'success' => false,
                    'error' => 'Bạn đã đặt cược cho round này'
                ], 400);
            }
            
            // Deduct balance
            $user->balance -= $amount;
            $user->save();
            
            // Create bet
            $bet = \App\Models\TradingBet::create([
                'user_id' => $user->id,
                'symbol' => $symbol,
                'direction' => $direction,
                'amount' => $amount,
                'payout_rate' => 1.95, // 95% profit
                'entry_price' => $entryPrice,
                'round_time' => $roundTime,
                'status' => 'pending',
            ]);
            
            return response()->json([
                'success' => true,
                'bet' => $bet,
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::placeBet error', [
                'message' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred while placing bet'
            ], 500);
        }
    }
    
    /**
     * Get bet result
     */
    public function getBetResult(Request $request)
    {
        try {
            $user = $request->user();
            if (!$user) {
                return response()->json([
                    'success' => false,
                    'error' => 'Unauthorized'
                ], 401);
            }
            
            $betId = $request->input('bet_id');
            $bet = \App\Models\TradingBet::where('id', $betId)
                ->where('user_id', $user->id)
                ->first();
            
            if (!$bet) {
                return response()->json([
                    'success' => false,
                    'error' => 'Bet not found'
                ], 404);
            }
            
            return response()->json([
                'success' => true,
                'bet' => $bet,
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::getBetResult error', [
                'message' => $e->getMessage(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred'
            ], 500);
        }
    }
    
    /**
     * Get bet ratio for current round
     */
    public function getBetRatio(Request $request)
    {
        try {
            $symbol = $request->input('symbol', 'BTCUSDT');
            $roundTime = (int)$request->input('round_time');
            
            $totalUp = \App\Models\TradingBet::where('symbol', $symbol)
                ->where('round_time', $roundTime)
                ->where('direction', 'up')
                ->where('status', 'pending')
                ->sum('amount');
            
            $totalDown = \App\Models\TradingBet::where('symbol', $symbol)
                ->where('round_time', $roundTime)
                ->where('direction', 'down')
                ->where('status', 'pending')
                ->sum('amount');
            
            $total = $totalUp + $totalDown;
            
            if ($total === 0) {
                return response()->json([
                    'success' => true,
                    'ratio_up' => 50,
                    'ratio_down' => 50,
                ]);
            }
            
            $ratioUp = round(($totalUp / $total) * 100, 1);
            $ratioDown = round(($totalDown / $total) * 100, 1);
            
            return response()->json([
                'success' => true,
                'ratio_up' => $ratioUp,
                'ratio_down' => $ratioDown,
            ]);
            
        } catch (\Exception $e) {
            Log::error('TradingController::getBetRatio error', [
                'message' => $e->getMessage(),
            ]);
            
            return response()->json([
                'success' => false,
                'error' => 'An error occurred'
            ], 500);
        }
    }
    
    private function getDefaultPrice(string $symbol): float
    {
        return match($symbol) {
            'BTCUSDT' => 94000,
            'ETHUSDT' => 3500,
            'BNBUSDT' => 600,
            'SOLUSDT' => 100,
            default => 1000,
        };
    }
}
