<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'phone_number',
        'display_name',
        'name',
        'email',
        'password',
        'referral_code',
        'referred_by',
        'transfer_code',
        'role',
        'balance',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /**
     * Get the name of the unique identifier for the user.
     *
     * @return string
     */
    public function getAuthIdentifierName()
    {
        return 'email';
    }

    /**
     * Relationship: Users referred by this user
     */
    public function referrals()
    {
        return $this->hasMany(User::class, 'referred_by');
    }

    /**
     * Relationship: User who referred this user
     */
    public function referrer()
    {
        return $this->belongsTo(User::class, 'referred_by');
    }

    /**
     * Check if user is admin
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    /**
     * Relationship: Deposit requests made by this user
     */
    public function depositRequests()
    {
        return $this->hasMany(DepositRequest::class);
    }

    /**
     * Relationship: Commissions received by this user
     */
    public function commissions()
    {
        return $this->hasMany(UserCommission::class, 'user_id');
    }

    /**
     * Relationship: Commissions generated by this user (from bets)
     */
    public function generatedCommissions()
    {
        return $this->hasMany(UserCommission::class, 'from_user_id');
    }

    /**
     * Get total available commission
     */
    public function getAvailableCommission()
    {
        return UserCommission::getAvailableCommission($this->id);
    }

    /**
     * Get the last approved deposit request
     */
    public function getLastApprovedDeposit()
    {
        return $this->depositRequests()
            ->where('status', 'approved')
            ->orderBy('approved_at', 'desc')
            ->first();
    }

    /**
     * Calculate total betting amount since last deposit
     * Returns the total amount of bets placed after the last approved deposit
     */
    public function getTotalBettingSinceLastDeposit()
    {
        $lastDeposit = $this->getLastApprovedDeposit();
        
        if (!$lastDeposit || !$lastDeposit->approved_at) {
            // No deposit yet, return 0
            return 0;
        }

        // Calculate total betting amount from bets created after the last deposit approval
        return \App\Models\Bet::where('user_id', $this->id)
            ->where('created_at', '>=', $lastDeposit->approved_at)
            ->sum('amount') ?? 0;
    }

    /**
     * Get remaining betting requirement (số đá quý cần cược thêm)
     * Returns the amount that still needs to be bet before withdrawal is allowed
     */
    public function getRemainingBettingRequirement()
    {
        $lastDeposit = $this->getLastApprovedDeposit();
        
        if (!$lastDeposit || !$lastDeposit->approved_at) {
            // No deposit yet, return 0 (no requirement)
            return 0;
        }

        $depositAmount = $lastDeposit->gem_amount ?? 0;
        $totalBetting = $this->getTotalBettingSinceLastDeposit();
        
        // Return remaining amount needed (if negative, means requirement is met)
        return max(0, $depositAmount - $totalBetting);
    }

    /**
     * Check if user has completed betting requirement
     * Returns true if total betting >= deposit amount since last deposit
     */
    public function hasCompletedBettingRequirement(): bool
    {
        $lastDeposit = $this->getLastApprovedDeposit();
        
        if (!$lastDeposit || !$lastDeposit->approved_at) {
            // No deposit yet, requirement is considered met
            return true;
        }

        $depositAmount = $lastDeposit->gem_amount ?? 0;
        $totalBetting = $this->getTotalBettingSinceLastDeposit();
        
        return $totalBetting >= $depositAmount;
    }
}
