<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'phone_number',
        'display_name',
        'name',
        'email',
        'password',
        'fund_password',
        'referral_code',
        'referred_by',
        'transfer_code',
        'role',
        'balance',
        'reward_balance',
        'last_reward_at',
        'last_bet_from_reward_at',
        'betting_requirement',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'balance' => 'decimal:2',
            'reward_balance' => 'decimal:2',
            'last_reward_at' => 'datetime',
            'last_bet_from_reward_at' => 'datetime',
            'betting_requirement' => 'decimal:2',
        ];
    }

    /**
     * Get the name of the unique identifier for the user.
     *
     * @return string
     */
    public function getAuthIdentifierName()
    {
        return 'email';
    }

    /**
     * Relationship: Users referred by this user
     */
    public function referrals()
    {
        return $this->hasMany(User::class, 'referred_by');
    }

    /**
     * Relationship: User who referred this user
     */
    public function referrer()
    {
        return $this->belongsTo(User::class, 'referred_by');
    }

    /**
     * Check if user is admin
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    /**
     * Relationship: Deposit requests made by this user
     */
    public function depositRequests()
    {
        return $this->hasMany(DepositRequest::class);
    }

    /**
     * Relationship: Commissions received by this user
     */
    public function commissions()
    {
        return $this->hasMany(UserCommission::class, 'user_id');
    }

    /**
     * Relationship: Commissions generated by this user (from bets)
     */
    public function generatedCommissions()
    {
        return $this->hasMany(UserCommission::class, 'from_user_id');
    }

    /**
     * Get total available commission
     */
    public function getAvailableCommission()
    {
        return UserCommission::getAvailableCommission($this->id);
    }

    /**
     * Get the last approved deposit request
     */
    public function getLastApprovedDeposit()
    {
        return $this->depositRequests()
            ->where('status', 'approved')
            ->orderBy('approved_at', 'desc')
            ->first();
    }

    /**
     * Calculate total betting amount (all time)
     * Returns the total amount of bets + betting contributions
     * Used to calculate remaining betting requirement: betting_requirement - total_betting
     */
    public function getTotalBettingSinceLastDeposit()
    {
        // Calculate total betting amount from all bets
        $betsAmount = \App\Models\Bet::where('user_id', $this->id)
            ->sum('amount') ?? 0;

        // Calculate total betting contributions (from giftcode, promotion, etc.)
        $contributionsAmount = \App\Models\BettingContribution::where('user_id', $this->id)
            ->sum('amount') ?? 0;

        return $betsAmount + $contributionsAmount;
    }

    /**
     * Check if user has completed betting requirement
     * Returns true if betting_requirement <= 0
     */
    public function hasCompletedBettingRequirement(): bool
    {
        $bettingRequirement = $this->betting_requirement ?? 0;
        return $bettingRequirement <= 0;
    }

    /**
     * Get count of subordinates who have deposited (approved deposits)
     */
    public function getDepositedSubordinatesCount()
    {
        // Get all subordinate IDs recursively
        $allSubordinateIds = $this->getAllSubordinateIds();
        
        // Count users who have at least one approved deposit
        return \App\Models\DepositRequest::whereIn('user_id', $allSubordinateIds)
            ->where('status', 'approved')
            ->distinct('user_id')
            ->count('user_id');
    }

    /**
     * Get all subordinate IDs recursively
     */
    public function getAllSubordinateIds()
    {
        return $this->_getAllSubordinateIdsRecursive($this->id);
    }
    
    /**
     * Helper method for recursive subordinate ID collection
     */
    private function _getAllSubordinateIdsRecursive($userId)
    {
        $ids = [];
        $directSubordinates = User::where('referred_by', $userId)->pluck('id')->toArray();
        
        foreach ($directSubordinates as $subId) {
            $ids[] = $subId;
            $ids = array_merge($ids, $this->_getAllSubordinateIdsRecursive($subId));
        }
        
        return $ids;
    }

    /**
     * Calculate user level based on number of deposited subordinates
     * LV2: 20 người đã nạp
     * LV3: 30 người đã nạp
     * LV4: 45 người đã nạp
     * LV5: 60 người đã nạp
     * LV6: 80 người đã nạp
     */
    public function getNetworkLevel()
    {
        $depositedCount = $this->getDepositedSubordinatesCount();
        
        if ($depositedCount >= 80) {
            return 6;
        } elseif ($depositedCount >= 60) {
            return 5;
        } elseif ($depositedCount >= 45) {
            return 4;
        } elseif ($depositedCount >= 30) {
            return 3;
        } elseif ($depositedCount >= 20) {
            return 2;
        } else {
            return 1;
        }
    }

    /**
     * Get maximum commission level based on network level
     * LV1: chỉ ăn F1
     * LV2: ăn F1-F2
     * LV3: ăn F1-F3
     * ...
     * LV6: ăn F1-F6
     */
    public function getMaxCommissionLevel()
    {
        $networkLevel = $this->getNetworkLevel();
        return $networkLevel; // Returns 1-6, which corresponds to F1-F6
    }

    /**
     * Get total available balance (deposit wallet + reward wallet)
     */
    public function getTotalBalance()
    {
        return ($this->balance ?? 0) + ($this->reward_balance ?? 0);
    }

    /**
     * Add reward to reward wallet
     */
    public function addReward($amount)
    {
        $this->reward_balance = ($this->reward_balance ?? 0) + $amount;
        $this->last_reward_at = now();
        $this->save();
    }

    /**
     * Transfer amount from reward wallet to deposit wallet
     * Returns true if successful, false otherwise
     */
    public function transferRewardToDeposit($amount)
    {
        if (($this->reward_balance ?? 0) < $amount) {
            return false;
        }

        $this->reward_balance -= $amount;
        $this->balance = ($this->balance ?? 0) + $amount;
        $this->save();

        return true;
    }

    /**
     * Check if reward balance should be expired (3 hours without betting from reward wallet)
     */
    public function shouldExpireRewardBalance()
    {
        if (($this->reward_balance ?? 0) <= 0) {
            return false;
        }

        // If never bet from reward wallet, check last_reward_at
        if ($this->last_bet_from_reward_at === null) {
            if ($this->last_reward_at === null) {
                return false;
            }
            $expireTime = $this->last_reward_at->copy()->addHours(3);
            return now() >= $expireTime;
        }

        // If bet from reward wallet, check last_bet_from_reward_at
        $expireTime = $this->last_bet_from_reward_at->copy()->addHours(3);
        return now() >= $expireTime;
    }

    /**
     * Expire reward balance (set to 0)
     */
    public function expireRewardBalance()
    {
        if (($this->reward_balance ?? 0) > 0) {
            $this->reward_balance = 0;
            $this->last_bet_from_reward_at = null;
            $this->save();
        }
    }

    /**
     * Deduct amount from wallets (ưu tiên ví nạp trước, nếu không đủ thì trừ từ ví thưởng)
     * Returns array with deducted amounts and source
     */
    public function deductFromWallets($amount)
    {
        $fromDeposit = 0;
        $fromReward = 0;
        $usedRewardWallet = false;

        $depositBalance = $this->balance ?? 0;
        $rewardBalance = $this->reward_balance ?? 0;

        if ($depositBalance >= $amount) {
            // Đủ trong ví nạp
            $fromDeposit = $amount;
            $this->balance -= $amount;
        } else {
            // Không đủ trong ví nạp, cần dùng cả 2 ví
            $fromDeposit = $depositBalance;
            $fromReward = $amount - $depositBalance;
            $this->balance = 0;
            $this->reward_balance -= $fromReward;
            $usedRewardWallet = true;
            
            // Cập nhật thời gian cược từ ví thưởng
            $this->last_bet_from_reward_at = now();
        }

        $this->save();

        return [
            'from_deposit' => $fromDeposit,
            'from_reward' => $fromReward,
            'used_reward_wallet' => $usedRewardWallet,
        ];
    }

    /**
     * Deduct amount from specific wallet (deposit or reward)
     * Returns array with deducted amounts and source
     */
    public function deductFromSpecificWallet($amount, $walletType = 'deposit')
    {
        $fromDeposit = 0;
        $fromReward = 0;
        $usedRewardWallet = false;

        if ($walletType === 'reward') {
            // Deduct from reward wallet only
            $rewardBalance = $this->reward_balance ?? 0;
            if ($rewardBalance < $amount) {
                throw new \Exception('Số dư ví thưởng không đủ để đặt cược.');
            }
            $fromReward = $amount;
            $this->reward_balance -= $amount;
            $usedRewardWallet = true;
            $this->last_bet_from_reward_at = now();
        } else {
            // Deduct from deposit wallet only
            $depositBalance = $this->balance ?? 0;
            if ($depositBalance < $amount) {
                throw new \Exception('Số dư ví nạp không đủ để đặt cược.');
            }
            $fromDeposit = $amount;
            $this->balance -= $amount;
        }

        $this->save();

        return [
            'from_deposit' => $fromDeposit,
            'from_reward' => $fromReward,
            'used_reward_wallet' => $usedRewardWallet,
        ];
    }
}
